<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Orders_model extends CI_Model
{

    public $table = 'orders';
    public $id = 'orderNumber';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('orderNumber,orderDate,requiredDate,shippedDate,status,comments,customerNumber');
        $this->datatables->from('orders');
        //add this line for join
        //$this->datatables->join('table2', 'orders.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('orders/read/$1'),'Read')." | ".anchor(site_url('orders/update/$1'),'Update')." | ".anchor(site_url('orders/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'orderNumber');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('orderNumber', $q);
	$this->db->or_like('orderDate', $q);
	$this->db->or_like('requiredDate', $q);
	$this->db->or_like('shippedDate', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('comments', $q);
	$this->db->or_like('customerNumber', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('orderNumber', $q);
	$this->db->or_like('orderDate', $q);
	$this->db->or_like('requiredDate', $q);
	$this->db->or_like('shippedDate', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('comments', $q);
	$this->db->or_like('customerNumber', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Orders_model.php */
/* Location: ./application/models/Orders_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-30 11:15:05 */
/* http://harviacode.com */