<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tchainhoist_model extends CI_Model
{

    public $table = 'TChainHoist';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,suket_no,lap_nama_perusahaan,lap_nama_pemakai,digunakan_untuk,tinggi_angkat,hoisting_speed,hoisting_motor,panjang_travelling,tinggi_girder,panjang_span,chain a,chain b,chain c,chain d,chain e,chain f,corrosion,wear,crack,deformation,hook a,hook b,hook c');
        $this->datatables->from('TChainHoist');
        //add this line for join
        //$this->datatables->join('table2', 'TChainHoist.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('tchainhoist/read/$1'),'Read')." | ".anchor(site_url('tchainhoist/update/$1'),'Update')." | ".anchor(site_url('tchainhoist/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('suket_no', $q);
	$this->db->or_like('lap_nama_perusahaan', $q);
	$this->db->or_like('lap_nama_pemakai', $q);
	$this->db->or_like('digunakan_untuk', $q);
	$this->db->or_like('tinggi_angkat', $q);
	$this->db->or_like('hoisting_speed', $q);
	$this->db->or_like('hoisting_motor', $q);
	$this->db->or_like('panjang_travelling', $q);
	$this->db->or_like('tinggi_girder', $q);
	$this->db->or_like('panjang_span', $q);
	$this->db->or_like('chain a', $q);
	$this->db->or_like('chain b', $q);
	$this->db->or_like('chain c', $q);
	$this->db->or_like('chain d', $q);
	$this->db->or_like('chain e', $q);
	$this->db->or_like('chain f', $q);
	$this->db->or_like('corrosion', $q);
	$this->db->or_like('wear', $q);
	$this->db->or_like('crack', $q);
	$this->db->or_like('deformation', $q);
	$this->db->or_like('hook a', $q);
	$this->db->or_like('hook b', $q);
	$this->db->or_like('hook c', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('suket_no', $q);
	$this->db->or_like('lap_nama_perusahaan', $q);
	$this->db->or_like('lap_nama_pemakai', $q);
	$this->db->or_like('digunakan_untuk', $q);
	$this->db->or_like('tinggi_angkat', $q);
	$this->db->or_like('hoisting_speed', $q);
	$this->db->or_like('hoisting_motor', $q);
	$this->db->or_like('panjang_travelling', $q);
	$this->db->or_like('tinggi_girder', $q);
	$this->db->or_like('panjang_span', $q);
	$this->db->or_like('chain a', $q);
	$this->db->or_like('chain b', $q);
	$this->db->or_like('chain c', $q);
	$this->db->or_like('chain d', $q);
	$this->db->or_like('chain e', $q);
	$this->db->or_like('chain f', $q);
	$this->db->or_like('corrosion', $q);
	$this->db->or_like('wear', $q);
	$this->db->or_like('crack', $q);
	$this->db->or_like('deformation', $q);
	$this->db->or_like('hook a', $q);
	$this->db->or_like('hook b', $q);
	$this->db->or_like('hook c', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tchainhoist_model.php */
/* Location: ./application/models/Tchainhoist_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-30 15:59:38 */
/* http://harviacode.com */