<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bapr_model extends CI_Model
{

    public $table = 'bapr';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,bapr_no,bapr_spd_no,bapr_tanggal,lokasi_objek,text_hari,text_tanggal,text_bulan,text_tahun,kelompok_uji,bapr_nama_alat,merk,serie,type,model,nomor_unit,kapasitas');
        $this->datatables->from('bapr');
        //add this line for join
        //$this->datatables->join('table2', 'bapr.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('bapr/read/$1'),'Read')." | ".anchor(site_url('bapr/update/$1'),'Update')." | ".anchor(site_url('bapr/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('bapr_no', $q);
	$this->db->or_like('bapr_spd_no', $q);
	$this->db->or_like('bapr_tanggal', $q);
	$this->db->or_like('lokasi_objek', $q);
	$this->db->or_like('text_hari', $q);
	$this->db->or_like('text_tanggal', $q);
	$this->db->or_like('text_bulan', $q);
	$this->db->or_like('text_tahun', $q);
	$this->db->or_like('kelompok_uji', $q);
	$this->db->or_like('bapr_nama_alat', $q);
	$this->db->or_like('merk', $q);
	$this->db->or_like('serie', $q);
	$this->db->or_like('type', $q);
	$this->db->or_like('model', $q);
	$this->db->or_like('nomor_unit', $q);
	$this->db->or_like('kapasitas', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('bapr_no', $q);
	$this->db->or_like('bapr_spd_no', $q);
	$this->db->or_like('bapr_tanggal', $q);
	$this->db->or_like('lokasi_objek', $q);
	$this->db->or_like('text_hari', $q);
	$this->db->or_like('text_tanggal', $q);
	$this->db->or_like('text_bulan', $q);
	$this->db->or_like('text_tahun', $q);
	$this->db->or_like('kelompok_uji', $q);
	$this->db->or_like('bapr_nama_alat', $q);
	$this->db->or_like('merk', $q);
	$this->db->or_like('serie', $q);
	$this->db->or_like('type', $q);
	$this->db->or_like('model', $q);
	$this->db->or_like('nomor_unit', $q);
	$this->db->or_like('kapasitas', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Bapr_model.php */
/* Location: ./application/models/Bapr_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-30 13:01:13 */
/* http://harviacode.com */